export const logs = [
    {
      id: 1,
      timestamp: "25/09/2024 14:32:15",
      user: "João Silva",
      action: "Edição",
      resource: "Ocorrência #OCR-2024-001523",
      ip: "192.168.1.45",
      details: {
        campo: "Status",
        anterior: "Pendente",
        atual: "Em Andamento",
        userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
        justificativa: "Equipe deslocada para local da ocorrência",
      },
    },
    {
      id: 2,
      timestamp: "26/09/2024 09:15:10",
      user: "Maria Santos",
      action: "Login",
      resource: "Dashboard",
      ip: "192.168.1.78",
      details: {
        campo: "-",
        anterior: "-",
        atual: "-",
        userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)",
        justificativa: "-",
      },
    },
    {
      id: 3,
      timestamp: "27/09/2024 11:22:34",
      user: "João Silva",
      action: "Criação",
      resource: "Relatórios",
      ip: "192.168.1.45",
      details: {
        campo: "Relatório",
        anterior: "-",
        atual: "Relatório Q3",
        userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
        justificativa: "Geração automática",
      },
    },
    // logs adicionais para teste (total > 10)
    {
      id: 4,
      timestamp: "01/10/2024 08:05:12",
      user: "Carlos Pereira",
      action: "Login",
      resource: "Dashboard",
      ip: "10.0.0.12",
      details: {
        campo: "-",
        anterior: "-",
        atual: "-",
        userAgent: "Mozilla/5.0 (X11; Linux x86_64)",
        justificativa: "-",
      },
    },
    {
      id: 5,
      timestamp: "02/10/2024 10:45:50",
      user: "Ana Lima",
      action: "Edição",
      resource: "Usuário: #USR-2024-004",
      ip: "172.16.0.5",
      details: {
        campo: "Email",
        anterior: "ana@old.com",
        atual: "ana@novo.com",
        userAgent: "Mozilla/5.0 (Windows NT 10.0)",
        justificativa: "Atualização solicitada pelo usuário",
      },
    },
    {
      id: 6,
      timestamp: "03/10/2024 12:12:12",
      user: "Pedro Costa",
      action: "Criação",
      resource: "Relatórios",
      ip: "192.168.1.99",
      details: {
        campo: "Relatório",
        anterior: "-",
        atual: "Relatório Especial",
        userAgent: "Mozilla/5.0 (Macintosh)",
        justificativa: "Geração manual",
      },
    },
    {
      id: 7,
      timestamp: "04/10/2024 13:22:22",
      user: "Maria Santos",
      action: "Edição",
      resource: "Ocorrência #OCR-2024-001600",
      ip: "192.168.1.78",
      details: {
        campo: "Prioridade",
        anterior: "Baixa",
        atual: "Alta",
        userAgent: "Mozilla/5.0 (Macintosh)",
        justificativa: "Reavaliação da equipe",
      },
    },
    {
      id: 8,
      timestamp: "05/10/2024 14:33:33",
      user: "João Silva",
      action: "Exclusão",
      resource: "Relatórios",
      ip: "192.168.1.45",
      details: {
        campo: "Relatório",
        anterior: "Relatório Antigo",
        atual: "-",
        userAgent: "Mozilla/5.0 (Windows NT 10.0)",
        justificativa: "Limpeza de dados",
      },
    },
    {
      id: 9,
      timestamp: "06/10/2024 15:44:44",
      user: "Carlos Pereira",
      action: "Login",
      resource: "Dashboard",
      ip: "10.0.0.12",
      details: {
        campo: "-",
        anterior: "-",
        atual: "-",
        userAgent: "curl/7.68.0",
        justificativa: "-",
      },
    },
    {
      id: 10,
      timestamp: "07/10/2024 16:55:55",
      user: "Ana Lima",
      action: "Edição",
      resource: "Usuário: #USR-2024-007",
      ip: "172.16.0.6",
      details: {
        campo: "Permissão",
        anterior: "Leitura",
        atual: "Leitura/Escrita",
        userAgent: "Mozilla/5.0 (Windows NT 10.0)",
        justificativa: "Promoção de cargo",
      },
    },
    {
      id: 11,
      timestamp: "08/10/2024 09:10:10",
      user: "Pedro Costa",
      action: "Login",
      resource: "Dashboard",
      ip: "192.168.1.99",
      details: {
        campo: "-",
        anterior: "-",
        atual: "-",
        userAgent: "Mozilla/5.0 (Macintosh)",
        justificativa: "-",
      },
    },
    {
      id: 12,
      timestamp: "09/10/2024 11:11:11",
      user: "João Silva",
      action: "Edição",
      resource: "Ocorrência #OCR-2024-002000",
      ip: "192.168.1.45",
      details: {
        campo: "Descrição",
        anterior: "Descrição antiga",
        atual: "Atualizada com novos dados",
        userAgent: "Mozilla/5.0 (Windows NT 10.0)",
        justificativa: "Correção de informações",
      },
    },
    {
      id: 13,
      timestamp: "10/10/2024 12:12:12",
      user: "Maria Santos",
      action: "Criação",
      resource: "Relatórios",
      ip: "192.168.1.78",
      details: {
        campo: "Relatório",
        anterior: "-",
        atual: "Relatório Mensal",
        userAgent: "Mozilla/5.0 (Macintosh)",
        justificativa: "Demanda gerencial",
      },
    },
    {
      id: 14,
      timestamp: "11/10/2024 13:13:13",
      user: "Carlos Pereira",
      action: "Edição",
      resource: "Usuário: #USR-2024-009",
      ip: "10.0.0.13",
      details: {
        campo: "Telefone",
        anterior: "0000-0000",
        atual: "1111-1111",
        userAgent: "Mozilla/5.0 (Linux)",
        justificativa: "Atualização de contato",
      },
    },
    {
      id: 15,
      timestamp: "12/10/2024 14:14:14",
      user: "Ana Lima",
      action: "Login",
      resource: "Dashboard",
      ip: "172.16.0.5",
      details: {
        campo: "-",
        anterior: "-",
        atual: "-",
        userAgent: "Mozilla/5.0 (Windows NT 10.0)",
        justificativa: "-",
      },
    },
    {
      id: 16,
      timestamp: "13/10/2024 15:15:15",
      user: "Pedro Costa",
      action: "Exclusão",
      resource: "Relatórios",
      ip: "192.168.1.99",
      details: {
        campo: "Relatório",
        anterior: "Relatório Antigo 2",
        atual: "-",
        userAgent: "Mozilla/5.0 (Macintosh)",
        justificativa: "Política de retenção",
      },
    },
    {
      id: 17,
      timestamp: "14/10/2024 16:16:16",
      user: "João Silva",
      action: "Login",
      resource: "Dashboard",
      ip: "192.168.1.45",
      details: {
        campo: "-",
        anterior: "-",
        atual: "-",
        userAgent: "Mozilla/5.0 (Windows NT 10.0)",
        justificativa: "-",
      },
    },
    {
      id: 18,
      timestamp: "15/10/2024 17:17:17",
      user: "Maria Santos",
      action: "Edição",
      resource: "Ocorrência #OCR-2024-002100",
      ip: "192.168.1.78",
      details: {
        campo: "Responsável",
        anterior: "Equipe A",
        atual: "Equipe B",
        userAgent: "Mozilla/5.0 (Macintosh)",
        justificativa: "Mudança de equipe responsável",
      },
    },
    {
      id: 19,
      timestamp: "16/10/2024 18:18:18",
      user: "João Silva",
      action: "Criação",
      resource: "Relatórios",
      ip: "192.168.1.45",
      details: {
        campo: "Relatório",
        anterior: "-",
        atual: "Relatório Trimestral",
        userAgent: "Mozilla/5.0 (Windows NT 10.0)",
        justificativa: "Geração automática trimestral",
      },
    },
    {
      id: 20,
      timestamp: "17/10/2024 19:19:19",
      user: "Maria Santos",
      action: "Exclusão",
      resource: "Ocorrência #OCR-2024-001700",
      ip: "192.168.1.78",
      details: {
        campo: "Ocorrência",
        anterior: "Ocorrência #OCR-2024-001700",
        atual: "-",
        userAgent: "Mozilla/5.0 (Macintosh)",
        justificativa: "Encerramento da ocorrência",
      },
    },
    {
      id: 21,
      timestamp: "18/10/2024 20:20:20",
      user: "Carlos Pereira",
      action: "Edição",
      resource: "Usuário: #USR-2024-010",
      ip: "10.0.0.14",
      details: {
        campo: "Cargo",
        anterior: "Analista",
        atual: "Coordenador",
        userAgent: "Mozilla/5.0 (Linux)",
        justificativa: "Promoção de cargo",
      },
    },
    {
      id: 22,
      timestamp: "19/10/2024 21:21:21",
      user: "Ana Lima",
      action: "Login",
      resource: "Dashboard",
      ip: "172.16.0.5",
      details: {
        campo: "-",
        anterior: "-",
        atual: "-",
        userAgent: "Mozilla/5.0 (Windows NT 10.0)",
        justificativa: "-",
      },
    },
    {
      id: 23,
      timestamp: "20/10/2024 22:22:22",
      user: "Pedro Costa",
      action: "Criação",
      resource: "Relatórios",
      ip: "192.168.1.99",
      details: {
        campo: "Relatório",
        anterior: "-",
        atual: "Relatório Anual",
        userAgent: "Mozilla/5.0 (Macintosh)",
        justificativa: "Geração automática anual",
      },
    },
    {
      id: 24,
      timestamp: "21/10/2024 23:23:23",
      user: "João Silva",
      action: "Edição",
      resource: "Ocorrência #OCR-2024-002200",
      ip: "192.168.1.45",
      details: {
        campo: "Descrição",
        anterior: "Descrição preliminar",
        atual: "Descrição atualizada",
        userAgent: "Mozilla/5.0 (Windows NT 10.0)",
        justificativa: "Atualização de descrição",
      },
    },
    {
      id: 25,
      timestamp: "22/10/2024 00:00:00",
      user: "Maria Santos",
      action: "Exclusão",
      resource: "Relatórios",
      ip: "192.168.1.78",
      details: {
        campo: "Relatório",
        anterior: "Relatório Mensal",
        atual: "-",
        userAgent: "Mozilla/5.0 (Macintosh)",
        justificativa: "Relatório não mais necessário",
      },
    },
    {
      id: 26,
      timestamp: "23/10/2024 01:01:01",
      user: "Carlos Pereira",
      action: "Login",
      resource: "Dashboard",
      ip: "10.0.0.14",
      details: {
        campo: "-",
        anterior: "-",
        atual: "-",
        userAgent: "Mozilla/5.0 (Linux)",
        justificativa: "-",
      },
    },
    {
      id: 27,
      timestamp: "24/10/2024 02:02:02",
      user: "Ana Lima",
      action: "Edição",
      resource: "Usuário: #USR-2024-011",
      ip: "172.16.0.6",
      details: {
        campo: "Senha",
        anterior: "********",
        atual: "********",
        userAgent: "Mozilla/5.0 (Windows NT 10.0)",
        justificativa: "Redefinição de senha",
      },
    },
    {
      id: 28,
      timestamp: "25/10/2024 03:03:03",
      user: "Pedro Costa",
      action: "Criação",
      resource: "Relatórios",
      ip: "192.168.1.99",
      details: {
        campo: "Relatório",
        anterior: "-",
        atual: "Relatório Semanal",
        userAgent: "Mozilla/5.0 (Macintosh)",
        justificativa: "Geração automática semanal",
      },
    },
    {
      id: 29,
      timestamp: "26/10/2024 04:04:04",
      user: "João Silva",
      action: "Edição",
      resource: "Ocorrência #OCR-2024-002300",
      ip: "192.168.1.45",
      details: {
        campo: "Status",
        anterior: "Em Andamento",
        atual: "Concluída",
        userAgent: "Mozilla/5.0 (Windows NT 10.0)",
        justificativa: "Ocorrência resolvida",
      },
    },
    {
      id: 30,
      timestamp: "27/10/2024 05:05:05",
      user: "Maria Santos",
      action: "Exclusão",
      resource: "Usuário: #USR-2024-012",
      ip: "192.168.1.78",
      details: {
        campo: "Usuário",
        anterior: "Usuário inativo",
        atual: "-",
        userAgent: "Mozilla/5.0 (Macintosh)",
        justificativa: "Usuário removido",
      },
    },
  ];